id: I67909F9B
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:21.031240
last_modified: 2023-01-04 11:30:21.031253
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  '7363':
    title: The Benefits of Saving Lives
    base_file: 7363.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
